name: module

description: "flutter app for traveler"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.2
  go_router: ^14.8.1
  dio: ^5.7.0
  build_runner: ^2.4.11
  injectable: ^2.5.0
  flutter_bloc: ^9.1.0
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  logger: ^2.5.0
  freezed: ^3.0.4
  freezed_annotation: ^3.0.0
  either_dart: ^1.0.0
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  socket_io_client: ^3.0.2
  photo_manager: ^3.6.3
  photo_manager_image_provider: ^2.2.0
  smooth_page_indicator: ^1.2.0+3
  cached_network_image: ^3.4.1
  supabase_flutter: ^2.8.4
  envied: ^1.1.1
  drift: ^2.20.3
  sqlite3_flutter_libs: ^0.5.31
  timeago: ^3.6.0
  mime: ^1.0.4
  http_parser: ^4.0.2
  uuid: ^4.0.0
  timeline_tile: ^2.0.0
  flutter_localizations:
    sdk: flutter
  pluto_grid: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  flutter_lints: ^3.0.0
  envied_generator: ^1.1.1
  drift_dev: ^2.20.3
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
